import json
import ollama
import sys
import re
from pathlib import Path

try:
    from test_integrated_defense import AegisSystem
except ModuleNotFoundError:
    print("[エラー] AegisSystemが見つかりません。")
    sys.exit(1)

class ResilientAgentLoop:
    def __init__(self, max_retries=3):
        self.aegis = AegisSystem()
        self.max_retries = max_retries

    def normalize_path(self, target_path: str) -> str:
        # AIの「忖度」を吸収: 先頭の不要なパス修飾を取り除く
        target_path = target_path.strip("./\\")
        prefix_to_remove = "jail_workspace/"
        if target_path.startswith(prefix_to_remove):
            target_path = target_path[len(prefix_to_remove):]
        # Windows環境でのバックスラッシュ表記にも対応
        prefix_to_remove_win = "jail_workspace\\"
        if target_path.startswith(prefix_to_remove_win):
            target_path = target_path[len(prefix_to_remove_win):]
        return target_path

    def extract_json(self, text: str) -> dict:
        # 余計な会話文を無視し、JSONオブジェクトのみを抽出
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if not match:
            raise ValueError("出力から有効なJSON構造を発見できませんでした。")
        return json.loads(match.group(0))

    def run(self, task: str):
        print("=== [Anjo-Core] 柔軟・自律型エージェントループ起動 ===")
        print(f"[システム] 指示: {task}\n")
        
        messages = [
            {'role': 'system', 'content': 'You are an autonomous agent. Output ONLY valid JSON. format: {"action": "write", "target": "filename", "content": "data"}'},
            {'role': 'user', 'content': task}
        ]

        for attempt in range(1, self.max_retries + 1):
            print(f"[試行 {attempt}/{self.max_retries}] Llama 3.1 が思考中...")
            
            response = ollama.chat(model='llama3.1', messages=messages)
            out = response['message']['content']
            
            # 出力が長すぎる場合は省略して表示
            display_out = out if len(out) < 200 else out[:200] + "\n... (以下省略)"
            print(f"[Ollama出力]\n{display_out}\n")

            try:
                # 1. 出力の正規化（JSONの抽出）
                parsed = self.extract_json(out)
                
                # 2. パスの「忖度」を吸収
                raw_target = parsed.get("target", "unknown.txt")
                normalized_target = self.normalize_path(raw_target)
                content = parsed.get("content", "")

                # 3. Aegisシステムによる防壁検閲
                safe_msg = self.aegis.execute_ai_intent("print('safe_text_operation')", normalized_target)
                print(safe_msg)

                # 4. 物理的書き込み（不足フォルダの自動生成含む）
                safe_path = self.aegis.jail.secure_resolve(normalized_target)
                safe_path.parent.mkdir(parents=True, exist_ok=True)
                with open(safe_path, "w", encoding="utf-8") as f:
                    f.write(content)

                print(f"\n=> [大成功!!] AIの揺らぎをシステムが吸収・補正し、タスクを完了しました。")
                print(f"=> 作成場所: {safe_path}")
                return # 成功した場合はここでループ終了

            except Exception as e:
                print(f"=> [システム: 遮断またはエラー] {e}")
                if attempt < self.max_retries:
                    print("=> AIにエラー内容をフィードバックし、自己修正を促します...\n")
                    # AIに自身の出力とエラー内容を渡し、修正を要求する
                    error_feedback = f"前回の出力でエラーが発生しました: {e}。余計なパス(jail_workspace/)や会話文を含めず、正しいJSON構造のみで再出力してください。"
                    messages.append({'role': 'assistant', 'content': out})
                    messages.append({'role': 'user', 'content': error_feedback})
                else:
                    print("\n=> [フェイルセーフ発動] 規定回数内でAIが正しい出力を生成できなかったため、安全のためにタスクを強制終了します。")

if __name__ == "__main__":
    task = "jail_workspace内に 'report.txt' というファイルを作成し、中に 'This report was successfully generated by adapting to AI behavior.' と書いてください。必ずJSON形式のみ ({\"action\": \"write\", \"target\": \"report.txt\", \"content\": \"<内容>\"}) で出力すること。"
    ResilientAgentLoop().run(task)
